[versions]
maimaihelper-name = "1.0.0"
maimaihelper-code = "1"

#noinspection AndroidGradlePluginVersion
android-gradle-plugin = "8.13.2"
kotlin = "2.1.0"
ktor = "3.0.3"

logback = "1.5.16"
google-zxing-core = "3.4.1"
google-zxing-javase = "3.2.0"
annotation-jvm = "1.9.1"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
google-zxing-core = { module = "com.google.zxing:core", version.ref = "google-zxing-core" }
google-zxing-javase = { module = "com.google.zxing:javase", version.ref = "google-zxing-javase" }
annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotation-jvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
